/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.unicesumar.mapa.prog2.interacao;
import com.unicesumar.mapa.prog2.senhas.*;

import java.util.List;
import java.util.ArrayList;


/**
 *
 * @author Diego
 */
public class Interface extends javax.swing.JFrame {
    
    private int contador = 1;
   
    List<Senha> senhas;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
       
        senhas = new ArrayList<Senha>();
    }
    
    private void geraSenha(String tipo){
        Senha senha = new Senha(tipo, contador++);
        senhas.add(senha);
        mostraSenha.setText(senha.retornaIdentificacao());
        
    }
    
    private void chamaSenha(int caixa, String tipo){

       

       //Procura o tipo, se achar atende, remove e sai

       for(int i=0; i<senhas.size();i++){

           if (senhas.get(i).retornaTipo().equals(tipo)){
               senhaChamada.setText(senhas.get(i).retornaIdentificacao());
               caixaDirecionado.setText("Caixa " + caixa);
               senhas.remove(i);
               return;
           }      
           


       }    
           if (senhas.size() > 0){
           senhaChamada.setText(senhas.get(0).retornaIdentificacao());
           caixaDirecionado.setText("Caixa "+ caixa);
           senhas.remove(0);
       }

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        RetiradaSenha = new javax.swing.JPanel();
        OrientacaoAtendimento = new javax.swing.JLabel();
        geraComum = new javax.swing.JButton();
        geraRapido = new javax.swing.JButton();
        geraPreferencial = new javax.swing.JButton();
        descreveSenha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostraSenha = new javax.swing.JTextArea();
        DirecaoCaixa = new javax.swing.JPanel();
        chamaCaixa1 = new javax.swing.JButton();
        chamaCaixa2 = new javax.swing.JButton();
        chamaCaixa3 = new javax.swing.JButton();
        chamaCaixa4 = new javax.swing.JButton();
        senhaChamada = new javax.swing.JLabel();
        caixaDirecionado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        RetiradaSenha.setBackground(new java.awt.Color(153, 153, 153));
        RetiradaSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        OrientacaoAtendimento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        OrientacaoAtendimento.setText("Escolha seu tipo de atendimento");

        geraComum.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        geraComum.setText("Comum");
        geraComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraComumActionPerformed(evt);
            }
        });

        geraRapido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        geraRapido.setText("Rápido");
        geraRapido.setMaximumSize(new java.awt.Dimension(107, 31));
        geraRapido.setMinimumSize(new java.awt.Dimension(107, 31));
        geraRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraRapidoActionPerformed(evt);
            }
        });

        geraPreferencial.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        geraPreferencial.setText("Prioritário");
        geraPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraPreferencialActionPerformed(evt);
            }
        });

        descreveSenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        descreveSenha.setText("Sua senha é:");

        mostraSenha.setColumns(1);
        mostraSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostraSenha.setRows(1);
        mostraSenha.setText("-");
        mostraSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(mostraSenha);

        javax.swing.GroupLayout RetiradaSenhaLayout = new javax.swing.GroupLayout(RetiradaSenha);
        RetiradaSenha.setLayout(RetiradaSenhaLayout);
        RetiradaSenhaLayout.setHorizontalGroup(
            RetiradaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetiradaSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RetiradaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RetiradaSenhaLayout.createSequentialGroup()
                        .addComponent(OrientacaoAtendimento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RetiradaSenhaLayout.createSequentialGroup()
                        .addGroup(RetiradaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RetiradaSenhaLayout.createSequentialGroup()
                                .addComponent(geraComum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(geraRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(geraPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descreveSenha))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(RetiradaSenhaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RetiradaSenhaLayout.setVerticalGroup(
            RetiradaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RetiradaSenhaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(OrientacaoAtendimento)
                .addGap(27, 27, 27)
                .addGroup(RetiradaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geraComum, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geraRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geraPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(descreveSenha)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        DirecaoCaixa.setBackground(new java.awt.Color(153, 153, 153));
        DirecaoCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para Caixa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        chamaCaixa1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        chamaCaixa1.setText("Caixa 1");
        chamaCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaCaixa1ActionPerformed(evt);
            }
        });

        chamaCaixa2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        chamaCaixa2.setText("Caixa 2");
        chamaCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaCaixa2ActionPerformed(evt);
            }
        });

        chamaCaixa3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        chamaCaixa3.setText("Caixa 3");
        chamaCaixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaCaixa3ActionPerformed(evt);
            }
        });

        chamaCaixa4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        chamaCaixa4.setText("Caixa 4");
        chamaCaixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaCaixa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DirecaoCaixaLayout = new javax.swing.GroupLayout(DirecaoCaixa);
        DirecaoCaixa.setLayout(DirecaoCaixaLayout);
        DirecaoCaixaLayout.setHorizontalGroup(
            DirecaoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DirecaoCaixaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(DirecaoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DirecaoCaixaLayout.createSequentialGroup()
                        .addComponent(chamaCaixa1)
                        .addGap(18, 18, 18)
                        .addComponent(chamaCaixa2)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(DirecaoCaixaLayout.createSequentialGroup()
                        .addComponent(chamaCaixa3)
                        .addGap(18, 18, 18)
                        .addComponent(chamaCaixa4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        DirecaoCaixaLayout.setVerticalGroup(
            DirecaoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DirecaoCaixaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(DirecaoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chamaCaixa1)
                    .addComponent(chamaCaixa2))
                .addGap(55, 55, 55)
                .addGroup(DirecaoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chamaCaixa3)
                    .addComponent(chamaCaixa4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        senhaChamada.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        senhaChamada.setText("Senha");

        caixaDirecionado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        caixaDirecionado.setText("Caixa");

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RetiradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DirecaoCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caixaDirecionado)
                            .addComponent(senhaChamada))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(senhaChamada)
                .addGap(31, 31, 31)
                .addComponent(caixaDirecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RetiradaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DirecaoCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geraComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraComumActionPerformed
        geraSenha("C");
    }//GEN-LAST:event_geraComumActionPerformed

    private void chamaCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaCaixa2ActionPerformed
        // TODO add your handling code here:
        chamaSenha(2,"R");
    }//GEN-LAST:event_chamaCaixa2ActionPerformed
        
    private void geraRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraRapidoActionPerformed
        geraSenha("R");
    }//GEN-LAST:event_geraRapidoActionPerformed

    private void geraPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraPreferencialActionPerformed
        geraSenha("P");
    }//GEN-LAST:event_geraPreferencialActionPerformed

    private void chamaCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaCaixa1ActionPerformed
        chamaSenha(1,"P");
    }//GEN-LAST:event_chamaCaixa1ActionPerformed

    private void chamaCaixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaCaixa3ActionPerformed
        chamaSenha(3,"R");    }//GEN-LAST:event_chamaCaixa3ActionPerformed

    private void chamaCaixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaCaixa4ActionPerformed
        chamaSenha(4,"C");
    }//GEN-LAST:event_chamaCaixa4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DirecaoCaixa;
    private javax.swing.JLabel OrientacaoAtendimento;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JPanel RetiradaSenha;
    private javax.swing.JLabel caixaDirecionado;
    private javax.swing.JButton chamaCaixa1;
    private javax.swing.JButton chamaCaixa2;
    private javax.swing.JButton chamaCaixa3;
    private javax.swing.JButton chamaCaixa4;
    private javax.swing.JLabel descreveSenha;
    private javax.swing.JButton geraComum;
    private javax.swing.JButton geraPreferencial;
    private javax.swing.JButton geraRapido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostraSenha;
    private javax.swing.JLabel senhaChamada;
    // End of variables declaration//GEN-END:variables
}
